usethis::use_build_ignore("devtools_history.R")
usethis::use_vignette("Utiliser-Vitefait")
devtools::document()
usethis::use_package("dplyr")
usethis::use_package("openxlsx")
usethis::use_package("lubridate")
usethis::use_package("stackoverflow")
usethis::use_package("DT")
usethis::use_package("shiny")
usethis::use_testthat()
devtools::test()
Sys.which(Sys.getenv("R_QPDF", "qpdf"))
Sys.setenv("R_QPDF" = "C:/Rtools/bin/qpdf.exe")
usethis::use_data(flights, overwrite = TRUE)
usethis::use_mit_license("Unedic")
devtools::load_all()
attachment::att_to_description()
devtools::check()
devtools::build()
